// Prime Fit — Exercise Library
// Gender-specific exercise programs with YouTube tutorial links

export interface Exercise {
  id: string;
  name: string;
  nameAr: string;
  category: string;
  categoryAr: string;
  sets: string;
  reps: string;
  rest: string; // in seconds
  restAr: string;
  youtubeUrl: string;
  imageUrl?: string;
  notes?: string;
  notesAr?: string;
}

export interface GenderProgram {
  goal: string;
  goalAr: string;
  schedule: string;
  scheduleAr: string;
  restBetweenSets: string;
  restBetweenSetsAr: string;
  tips: string[];
  tipsAr: string[];
  weeklyPlan: string[];
  weeklyPlanAr: string[];
  exercises: Exercise[];
}

// ── WOMEN'S PROGRAM ──────────────────────────────────────────────────────────
export const womenProgram: GenderProgram = {
  goal: "Tone the body, build balanced feminine muscles, and improve fitness.",
  goalAr: "شد الجسم، بناء عضلات أنثوية متناسقة، وتحسين اللياقة.",
  schedule: "3–5 days per week",
  scheduleAr: "3–5 أيام بالأسبوع",
  restBetweenSets: "45–90 seconds depending on exercise intensity",
  restBetweenSetsAr: "45–90 ثانية حسب شدة التمرين",
  tips: [
    "Always start with 5–10 minutes of cardio warm-up.",
    "Focus on slow movement and weight control.",
    "Gradually increase weights over time.",
    "Sleep and nutrition are essential for visible results.",
    "Split your workouts: Upper day / Lower + Glutes day / Back + Core day / Rest or Cardio.",
  ],
  tipsAr: [
    "ابدئي دائمًا بـ 5–10 دقائق إحماء كارديو.",
    "ركزي على الحركة البطيئة والتحكم بالوزن.",
    "زيدي الأوزان تدريجيًا مع الوقت.",
    "النوم والتغذية مهمين جدًا لظهور النتائج.",
    "يمكن تقسيم التمارين: يوم علوي / يوم سفلي + أرداف / يوم ظهر + بطن / يوم راحة أو كارديو.",
  ],
  weeklyPlan: [
    "Day 1: Upper Body (Shoulders + Chest + Arms)",
    "Day 2: Lower Body + Glutes",
    "Day 3: Back + Core",
    "Day 4: Rest or Light Cardio",
    "Day 5: Repeat cycle",
  ],
  weeklyPlanAr: [
    "اليوم 1: جزء علوي (أكتاف + صدر + ذراع)",
    "اليوم 2: جزء سفلي + أرداف",
    "اليوم 3: ظهر + بطن",
    "اليوم 4: راحة أو كارديو خفيف",
    "اليوم 5: تكرار الدورة",
  ],
  exercises: [
    // ── SHOULDERS ──
    {
      id: "w-shoulder-press",
      name: "Shoulder Press Machine",
      nameAr: "جهاز Shoulder Press",
      category: "Shoulders",
      categoryAr: "الأكتاف",
      sets: "4",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=qEwKCR5JCog",
      imageUrl: "/manus-storage/shoulder_exercises_b5f42a3f.jpg",
      notes: "Keep back straight, press upward smoothly",
      notesAr: "حافظي على استقامة الظهر، ادفعي للأعلى بسلاسة",
    },
    {
      id: "w-lateral-raise",
      name: "Lateral Raise Machine",
      nameAr: "جهاز Lateral Raise",
      category: "Shoulders",
      categoryAr: "الأكتاف",
      sets: "3",
      reps: "12–15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=3VcKaXpzqRo",
      imageUrl: "/manus-storage/shoulder_exercises_b5f42a3f.jpg",
      notes: "Raise arms to shoulder height, controlled movement",
      notesAr: "ارفعي الذراعين لمستوى الكتف، حركة متحكمة",
    },
    // ── CHEST ──
    {
      id: "w-chest-press",
      name: "Chest Press Machine",
      nameAr: "جهاز Chest Press",
      category: "Chest",
      categoryAr: "الصدر",
      sets: "4",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=U5uW6jaOiLg",
      imageUrl: "/manus-storage/chest_shoulder_f1405bff.jpg",
      notes: "Squeeze chest at the top of movement",
      notesAr: "اضغطي عضلة الصدر عند نهاية الحركة",
    },
    {
      id: "w-pec-deck",
      name: "Pec Deck Machine",
      nameAr: "جهاز Pec Deck (تفتيح صدر)",
      category: "Chest",
      categoryAr: "الصدر",
      sets: "3",
      reps: "12–15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=Z57CtFmRMxA",
      imageUrl: "/manus-storage/chest_shoulder_f1405bff.jpg",
      notes: "Controlled arc motion, feel the stretch",
      notesAr: "حركة قوسية متحكمة، أحسسي بالشد",
    },
    // ── ARMS ──
    {
      id: "w-biceps-curl",
      name: "Biceps Curl Machine",
      nameAr: "جهاز Biceps Curl",
      category: "Arms",
      categoryAr: "الذراع",
      sets: "3",
      reps: "12",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=ykJmrZ5v0Oo",
      imageUrl: "/manus-storage/arm_exercises_5b84dfc6.jpg",
      notes: "Full range of motion, squeeze at top",
      notesAr: "نطاق حركة كامل، اضغطي في الأعلى",
    },
    {
      id: "w-triceps-pushdown",
      name: "Triceps Pushdown Machine",
      nameAr: "جهاز Triceps Pushdown",
      category: "Arms",
      categoryAr: "الذراع",
      sets: "3",
      reps: "12–15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=2-LAMcpzODU",
      imageUrl: "/manus-storage/arm_exercises_5b84dfc6.jpg",
      notes: "Keep elbows close to body",
      notesAr: "أبقي المرفقين قريبين من الجسم",
    },
    // ── BACK ──
    {
      id: "w-lat-pulldown",
      name: "Lat Pulldown Machine",
      nameAr: "جهاز Lat Pulldown",
      category: "Back",
      categoryAr: "الظهر",
      sets: "4",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=CAwf7n6Luuc",
      imageUrl: "/manus-storage/lat_pulldown_fac5d232.jpg",
      notes: "Pull to upper chest, squeeze shoulder blades",
      notesAr: "اسحبي لأعلى الصدر، اضغطي لوحي الكتف",
    },
    {
      id: "w-seated-row",
      name: "Seated Row Machine",
      nameAr: "جهاز Seated Row",
      category: "Back",
      categoryAr: "الظهر",
      sets: "4",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=GZbfZ033f74",
      imageUrl: "/manus-storage/lat_pulldown_fac5d232.jpg",
      notes: "Pull elbows back, squeeze back muscles",
      notesAr: "اسحبي المرفقين للخلف، اضغطي عضلات الظهر",
    },
    {
      id: "w-back-extension",
      name: "Back Extension Machine",
      nameAr: "جهاز Back Extension",
      category: "Back",
      categoryAr: "الظهر",
      sets: "3",
      reps: "15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=ph3pddpKzzw",
      imageUrl: "/manus-storage/lat_pulldown_fac5d232.jpg",
      notes: "Controlled movement, don't hyperextend",
      notesAr: "حركة متحكمة، لا تبالغي في التمديد",
    },
    // ── CORE ──
    {
      id: "w-ab-crunch",
      name: "Ab Crunch Machine",
      nameAr: "جهاز Ab Crunch",
      category: "Core",
      categoryAr: "منطقة البطن",
      sets: "4",
      reps: "15–20",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=MKmrqcoCZ-M",
      notes: "Exhale on the crunch, slow return",
      notesAr: "ازفري عند الانقباض، عودة بطيئة",
    },
    {
      id: "w-cable-crunch",
      name: "Cable Crunch",
      nameAr: "جهاز Cable Crunch",
      category: "Core",
      categoryAr: "منطقة البطن",
      sets: "3",
      reps: "15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=2fbujeH3F0E",
      notes: "Round the back, focus on abs contraction",
      notesAr: "قوسي الظهر، ركزي على انقباض البطن",
    },
    {
      id: "w-captain-chair",
      name: "Captain Chair Leg Raise",
      nameAr: "رفع الأرجل على جهاز Captain Chair",
      category: "Core",
      categoryAr: "منطقة البطن",
      sets: "3",
      reps: "12–15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=Ss7Tv4NiQRk",
      notes: "Controlled leg raise, no swinging",
      notesAr: "رفع الأرجل بتحكم، بدون تأرجح",
    },
    // ── CHEST (continued) ──
    {
      id: "w-cable-crossover",
      name: "Cable Crossover",
      nameAr: "كابل كروس أوفر",
      category: "Chest",
      categoryAr: "الصدر",
      sets: "3",
      reps: "12–15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=taI4XduLpTk",
      notes: "Keep slight bend in elbows, squeeze chest at center",
      notesAr: "أبقي انحناء طفيف في المرفقين، اضغطي الصدر في المنتصف",
    },
    // ── CORE (continued) ──
    {
      id: "w-oblique-twist",
      name: "Oblique Twist Machine",
      nameAr: "جهاز الالتواء الجانبي",
      category: "Core",
      categoryAr: "منطقة البطن",
      sets: "3",
      reps: "15 per side",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=97boSjZ0erk",
      notes: "Rotate from core, not hips",
      notesAr: "الدوران من الكور وليس الورك",
    },
    // ── GLUTES ──
    {
      id: "w-hip-thrust",
      name: "Hip Thrust Machine",
      nameAr: "جهاز Hip Thrust",
      category: "Glutes",
      categoryAr: "الأرداف",
      sets: "4",
      reps: "10–12",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=SEdqd1n0cvg",
      notes: "Squeeze glutes at the top, full hip extension",
      notesAr: "اضغطي الأرداف في الأعلى، تمديد كامل للورك",
    },
    {
      id: "w-glute-kickback",
      name: "Glute Kickback Machine",
      nameAr: "جهاز Glute Kickback",
      category: "Glutes",
      categoryAr: "الأرداف",
      sets: "4",
      reps: "12–15 per leg",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=97boSjZ0erk",
      notes: "Squeeze glute at peak, slow return",
      notesAr: "اضغطي الردف في الذروة، عودة بطيئة",
    },
    {
      id: "w-hip-abductor",
      name: "Hip Abductor Machine",
      nameAr: "جهاز Hip Abductor",
      category: "Glutes",
      categoryAr: "الأرداف",
      sets: "4",
      reps: "15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=OjI5OpV6IWA",
      notes: "Slow controlled outward movement",
      notesAr: "حركة خارجية بطيئة ومتحكمة",
    },
    {
      id: "w-hip-adductor",
      name: "Hip Adductor Machine",
      nameAr: "جهاز Hip Adductor",
      category: "Glutes",
      categoryAr: "الأرداف",
      sets: "4",
      reps: "15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=OjI5OpV6IWA",
      notes: "Slow controlled inward movement, squeeze inner thighs",
      notesAr: "حركة داخلية بطيئة ومتحكمة، اضغطي عضلات الفخذ الداخلية",
    },
    // ── LEGS ──
    {
      id: "w-leg-press",
      name: "Leg Press Machine",
      nameAr: "جهاز Leg Press",
      category: "Legs",
      categoryAr: "الساق",
      sets: "4",
      reps: "10–12",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
      imageUrl: "/manus-storage/lunges_squats_70531127.jpg",
      notes: "Don't lock knees at top, controlled descent",
      notesAr: "لا تقفلي الركبتين في الأعلى، نزول متحكم",
    },
    {
      id: "w-leg-extension",
      name: "Leg Extension Machine",
      nameAr: "جهاز Leg Extension",
      category: "Legs",
      categoryAr: "الساق",
      sets: "3",
      reps: "12–15",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=YyvSfVjQeL0",
      imageUrl: "/manus-storage/glutes_0a523f53.jpg",
      notes: "Full extension, squeeze quads at top",
      notesAr: "تمديد كامل، اضغطي عضلة الفخذ في الأعلى",
    },
    {
      id: "w-leg-curl",
      name: "Leg Curl Machine",
      nameAr: "جهاز Leg Curl",
      category: "Legs",
      categoryAr: "الساق",
      sets: "3",
      reps: "12–15",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=1Tq3QdYUuHs",
      imageUrl: "/manus-storage/glutes_0a523f53.jpg",
      notes: "Slow controlled curl, full range",
      notesAr: "ثني بطيء ومتحكم، نطاق كامل",
    },
    {
      id: "w-calf-raise",
      name: "Calf Raise Machine",
      nameAr: "جهاز Calf Raise",
      category: "Legs",
      categoryAr: "الساق",
      sets: "4",
      reps: "15–20",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=baEXLy09Ncc",
      imageUrl: "/manus-storage/glutes_0a523f53.jpg",
      notes: "Full range, pause at top and bottom",
      notesAr: "نطاق كامل، توقف في الأعلى والأسفل",
    },
  ],
};

// ── MEN'S PROGRAM ────────────────────────────────────────────────────────────
export const menProgram: GenderProgram = {
  goal: "Build muscle, increase strength, and improve muscular symmetry.",
  goalAr: "بناء عضلات، زيادة القوة، وتحسين التناسق العضلي.",
  schedule: "4–6 days per week",
  scheduleAr: "4–6 أيام بالأسبوع",
  restBetweenSets: "Heavy: 90–120s | Medium: 60–90s | Isolation: 45–60s",
  restBetweenSetsAr: "تمارين ثقيلة: 90–120 ث | متوسطة: 60–90 ث | عزل: 45–60 ث",
  tips: [
    "Focus on correct form before increasing weight.",
    "Try to increase weight or reps progressively each week.",
    "Protein and sleep are essential for muscle building.",
    "Cardio 2–3 times per week helps fitness and definition.",
    "Never skip leg day — it's key for full muscular balance.",
  ],
  tipsAr: [
    "ركز على الأداء الصحيح قبل زيادة الوزن.",
    "حاول زيادة الوزن أو التكرارات تدريجيًا أسبوعيًا.",
    "البروتين والنوم أساسيان لبناء العضلات.",
    "الكارديو 2–3 مرات أسبوعيًا يساعد على اللياقة والتنشيف.",
    "لا تهمل تمارين الأرجل لتحقيق توازن عضلي كامل.",
  ],
  weeklyPlan: [
    "Day 1: Chest + Triceps",
    "Day 2: Back + Biceps",
    "Day 3: Rest",
    "Day 4: Shoulders + Core",
    "Day 5: Full Legs",
    "Day 6–7: Rest or Cardio",
  ],
  weeklyPlanAr: [
    "اليوم 1: صدر + ترايسبس",
    "اليوم 2: ظهر + بايسبس",
    "اليوم 3: راحة",
    "اليوم 4: أكتاف + بطن",
    "اليوم 5: أرجل كاملة",
    "اليوم 6–7: راحة أو كارديو",
  ],
  exercises: [
    // ── CHEST ──
    {
      id: "m-chest-press",
      name: "Chest Press Machine",
      nameAr: "جهاز Chest Press",
      category: "Chest",
      categoryAr: "الصدر",
      sets: "4",
      reps: "8–12",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=U5uW6jaOiLg",
      imageUrl: "/manus-storage/chest_shoulder_f1405bff.jpg",
      notes: "Full range, squeeze chest at top",
      notesAr: "نطاق كامل، اضغط عضلة الصدر في الأعلى",
    },
    {
      id: "m-incline-chest-press",
      name: "Incline Chest Press Machine",
      nameAr: "جهاز Incline Chest Press",
      category: "Chest",
      categoryAr: "الصدر",
      sets: "4",
      reps: "10",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=DbFgADa2PL8",
      notes: "Targets upper chest, controlled descent",
      notesAr: "يستهدف الصدر العلوي، نزول متحكم",
    },
    {
      id: "m-pec-deck",
      name: "Pec Deck Machine",
      nameAr: "جهاز Pec Deck",
      category: "Chest",
      categoryAr: "الصدر",
      sets: "3",
      reps: "12–15",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=Z57CtFmRMxA",
      imageUrl: "/manus-storage/chest_shoulder_f1405bff.jpg",
      notes: "Feel the stretch, controlled arc",
      notesAr: "أحس بالشد، قوس متحكم",
    },
    // ── BACK ──
    {
      id: "m-lat-pulldown",
      name: "Lat Pulldown Machine",
      nameAr: "جهاز Lat Pulldown",
      category: "Back",
      categoryAr: "الظهر",
      sets: "4",
      reps: "8–12",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=CAwf7n6Luuc",
      imageUrl: "/manus-storage/lat_pulldown_fac5d232.jpg",
      notes: "Pull to upper chest, squeeze lats",
      notesAr: "اسحب لأعلى الصدر، اضغط العضلة الظهرية",
    },
    {
      id: "m-seated-row",
      name: "Seated Row Machine",
      nameAr: "جهاز Seated Row",
      category: "Back",
      categoryAr: "الظهر",
      sets: "4",
      reps: "10–12",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=GZbfZ033f74",
      imageUrl: "/manus-storage/lat_pulldown_fac5d232.jpg",
      notes: "Pull elbows back, full contraction",
      notesAr: "اسحب المرفقين للخلف، انقباض كامل",
    },
    {
      id: "m-hammer-row",
      name: "Hammer Row Machine",
      nameAr: "جهاز Hammer Row",
      category: "Back",
      categoryAr: "الظهر",
      sets: "3",
      reps: "10",
      rest: "75",
      restAr: "75 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=Ss7Tv4NiQRk",
      notes: "Neutral grip, retract shoulder blades",
      notesAr: "قبضة محايدة، اسحب لوحي الكتف للخلف",
    },
    {
      id: "m-back-extension",
      name: "Back Extension Machine",
      nameAr: "جهاز Back Extension",
      category: "Back",
      categoryAr: "الظهر",
      sets: "3",
      reps: "15",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=ph3pddpKzzw",
      imageUrl: "/manus-storage/lat_pulldown_fac5d232.jpg",
      notes: "Controlled, don't hyperextend",
      notesAr: "متحكم، لا تبالغ في التمديد",
    },
    // ── SHOULDERS ──
    {
      id: "m-shoulder-press",
      name: "Shoulder Press Machine",
      nameAr: "جهاز Shoulder Press",
      category: "Shoulders",
      categoryAr: "الأكتاف",
      sets: "4",
      reps: "10",
      rest: "75",
      restAr: "75 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=qEwKCR5JCog",
      imageUrl: "/manus-storage/shoulder_exercises_b5f42a3f.jpg",
      notes: "Press overhead, don't shrug",
      notesAr: "ادفع للأعلى، لا ترفع الكتفين",
    },
    {
      id: "m-lateral-raise",
      name: "Lateral Raise Machine",
      nameAr: "جهاز Lateral Raise",
      category: "Shoulders",
      categoryAr: "الأكتاف",
      sets: "4",
      reps: "12–15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=3VcKaXpzqRo",
      imageUrl: "/manus-storage/shoulder_exercises_b5f42a3f.jpg",
      notes: "Lead with elbows, raise to shoulder height",
      notesAr: "قُد بالمرفقين، ارفع لمستوى الكتف",
    },
    {
      id: "m-rear-delt-fly",
      name: "Rear Delt Fly Machine",
      nameAr: "جهاز Rear Delt Fly",
      category: "Shoulders",
      categoryAr: "الأكتاف",
      sets: "3",
      reps: "12–15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=EA7u4Q_8HQ0",
      imageUrl: "/manus-storage/shoulder_exercises_b5f42a3f.jpg",
      notes: "Squeeze rear delts, slow return",
      notesAr: "اضغط الكتف الخلفي، عودة بطيئة",
    },
    // ── ARMS ──
    {
      id: "m-biceps-curl",
      name: "Biceps Curl Machine",
      nameAr: "جهاز Biceps Curl",
      category: "Arms",
      categoryAr: "الذراع",
      sets: "4",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=ykJmrZ5v0Oo",
      imageUrl: "/manus-storage/arm_exercises_5b84dfc6.jpg",
      notes: "Full range, peak contraction at top",
      notesAr: "نطاق كامل، انقباض قمة في الأعلى",
    },
    {
      id: "m-preacher-curl",
      name: "Preacher Curl Machine",
      nameAr: "جهاز Preacher Curl",
      category: "Arms",
      categoryAr: "الذراع",
      sets: "3",
      reps: "12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=fIWP-FRFNU0",
      imageUrl: "/manus-storage/arm_exercises_5b84dfc6.jpg",
      notes: "Isolates biceps, controlled negative",
      notesAr: "يعزل البايسبس، نزول متحكم",
    },
    {
      id: "m-triceps-pushdown",
      name: "Triceps Pushdown Machine",
      nameAr: "جهاز Triceps Pushdown",
      category: "Arms",
      categoryAr: "الذراع",
      sets: "4",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=2-LAMcpzODU",
      imageUrl: "/manus-storage/arm_exercises_5b84dfc6.jpg",
      notes: "Keep elbows fixed, full extension",
      notesAr: "أبقِ المرفقين ثابتين، تمديد كامل",
    },
    {
      id: "m-dip-machine",
      name: "Dip Machine",
      nameAr: "جهاز Dip Machine",
      category: "Arms",
      categoryAr: "الذراع",
      sets: "3",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=wjUmnZH528Y",
      imageUrl: "/manus-storage/arm_exercises_5b84dfc6.jpg",
      notes: "Lean slightly forward for chest focus",
      notesAr: "انحنِ للأمام قليلاً للتركيز على الصدر",
    },
    // ── CHEST (continued) ──
    {
      id: "m-cable-crossover",
      name: "Cable Crossover",
      nameAr: "كابل كروس أوفر",
      category: "Chest",
      categoryAr: "الصدر",
      sets: "3",
      reps: "12–15",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=taI4XduLpTk",
      notes: "Keep slight bend in elbows, squeeze chest at center",
      notesAr: "أبقِ انحناء طفيف في المرفقين، اضغط الصدر في المنتصف",
    },
    // ── CORE ──
    {
      id: "m-ab-crunch",
      name: "Ab Crunch Machine",
      nameAr: "جهاز Ab Crunch",
      category: "Core",
      categoryAr: "البطن",
      sets: "4",
      reps: "15–20",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=MKmrqcoCZ-M",
      notes: "Exhale on crunch, slow return",
      notesAr: "ازفر عند الانقباض، عودة بطيئة",
    },
    {
      id: "m-cable-crunch",
      name: "Cable Crunch",
      nameAr: "جهاز Cable Crunch",
      category: "Core",
      categoryAr: "البطن",
      sets: "4",
      reps: "15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=2fbujeH3F0E",
      notes: "Round the back, abs do the work",
      notesAr: "قوس الظهر، البطن يقوم بالعمل",
    },
    {
      id: "m-leg-raise",
      name: "Hanging Leg Raise",
      nameAr: "رفع الأرجل",
      category: "Core",
      categoryAr: "البطن",
      sets: "3",
      reps: "15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=hdng3Nm1x_E",
      notes: "Controlled raise, no swinging",
      notesAr: "رفع متحكم، بدون تأرجح",
    },
    {
      id: "m-oblique-twist",
      name: "Oblique Twist Machine",
      nameAr: "جهاز الالتواء الجانبي",
      category: "Core",
      categoryAr: "البطن",
      sets: "3",
      reps: "15 per side",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=97boSjZ0erk",
      notes: "Rotate from core, not hips",
      notesAr: "الدوران من الكور وليس الورك",
    },
    // ── LEGS ──
    {
      id: "m-leg-press",
      name: "Leg Press Machine",
      nameAr: "جهاز Leg Press",
      category: "Legs",
      categoryAr: "الساق والأرداف",
      sets: "4",
      reps: "10–12",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
      imageUrl: "/manus-storage/lunges_squats_70531127.jpg",
      notes: "Don't lock knees, full depth",
      notesAr: "لا تقفل الركبتين، عمق كامل",
    },
    {
      id: "m-squat-machine",
      name: "Squat Machine (Smith/Hack)",
      nameAr: "جهاز Squat Machine",
      category: "Legs",
      categoryAr: "الساق والأرداف",
      sets: "4",
      reps: "8–10",
      rest: "120",
      restAr: "120 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=U3HlEF_E9fo",
      imageUrl: "/manus-storage/lunges_squats_70531127.jpg",
      notes: "Deep squat, chest up, knees track toes",
      notesAr: "سكوات عميق، صدر للأعلى، ركبتان تتبعان القدمين",
    },
    {
      id: "m-leg-extension",
      name: "Leg Extension Machine",
      nameAr: "جهاز Leg Extension",
      category: "Legs",
      categoryAr: "الساق والأرداف",
      sets: "4",
      reps: "12–15",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=YyvSfVjQeL0",
      imageUrl: "/manus-storage/glutes_0a523f53.jpg",
      notes: "Squeeze quads at full extension",
      notesAr: "اضغط عضلة الفخذ عند التمديد الكامل",
    },
    {
      id: "m-leg-curl",
      name: "Leg Curl Machine",
      nameAr: "جهاز Leg Curl",
      category: "Legs",
      categoryAr: "الساق والأرداف",
      sets: "4",
      reps: "12–15",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=1Tq3QdYUuHs",
      imageUrl: "/manus-storage/glutes_0a523f53.jpg",
      notes: "Full range, slow eccentric",
      notesAr: "نطاق كامل، نزول بطيء",
    },
    {
      id: "m-calf-raise",
      name: "Calf Raise Machine",
      nameAr: "جهاز Calf Raise",
      category: "Legs",
      categoryAr: "الساق والأرداف",
      sets: "5",
      reps: "15–20",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=baEXLy09Ncc",
      imageUrl: "/manus-storage/glutes_0a523f53.jpg",
      notes: "Full range, pause at top and bottom",
      notesAr: "نطاق كامل، توقف في الأعلى والأسفل",
    },
    {
      id: "m-hip-abductor",
      name: "Hip Abductor Machine",
      nameAr: "جهاز Hip Abductor",
      category: "Legs",
      categoryAr: "الساق والأرداف",
      sets: "4",
      reps: "15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=OjI5OpV6IWA",
      notes: "Slow controlled outward movement",
      notesAr: "حركة خارجية بطيئة ومتحكمة",
    },
    {
      id: "m-hip-adductor",
      name: "Hip Adductor Machine",
      nameAr: "جهاز Hip Adductor",
      category: "Legs",
      categoryAr: "الساق والأرداف",
      sets: "4",
      reps: "15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=OjI5OpV6IWA",
      notes: "Slow controlled inward movement, squeeze inner thighs",
      notesAr: "حركة داخلية بطيئة ومتحكمة، اضغط عضلات الفخذ الداخلية",
    },
  ],
};

export function getProgramByGender(gender: "male" | "female"): GenderProgram {
  return gender === "female" ? womenProgram : menProgram;
}

export function getExercisesByCategory(
  gender: "male" | "female"
): Record<string, Exercise[]> {
  const program = getProgramByGender(gender);
  const grouped: Record<string, Exercise[]> = {};
  for (const ex of program.exercises) {
    if (!grouped[ex.category]) grouped[ex.category] = [];
    grouped[ex.category].push(ex);
  }
  return grouped;
}

// ── SHARED NEW CATEGORY EXERCISES (used by both genders via SESSION_CATEGORY_MAP) ──
export const newCategoryExercises: Exercise[] = [
  // ── WARM-UP ──
  {
    id: 'warmup_neck_rolls',
    name: 'Neck Rolls',
    nameAr: 'دوران الرقبة',
    category: 'Warm-Up',
    categoryAr: 'الإحماء',
    sets: '1', reps: '10 each side', rest: '0', restAr: '0 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=2M80Mn0VBPw',
    notes: 'Slow and controlled, loosen neck muscles',
    notesAr: 'ببطء وتحكم، لإرخاء عضلات الرقبة',
  },
  {
    id: 'warmup_arm_circles',
    name: 'Arm Circles',
    nameAr: 'دوران الذراعين',
    category: 'Warm-Up',
    categoryAr: 'الإحماء',
    sets: '1', reps: '15 forward + 15 back', rest: '0', restAr: '0 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=140RTNMciH8',
    notes: 'Warm up shoulder joints',
    notesAr: 'لتدفئة مفاصل الكتف',
  },
  {
    id: 'warmup_hip_circles',
    name: 'Hip Circles',
    nameAr: 'دوران الورك',
    category: 'Warm-Up',
    categoryAr: 'الإحماء',
    sets: '1', reps: '10 each direction', rest: '0', restAr: '0 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=JYqLwajOGjI',
    notes: 'Loosen hip joints before workout',
    notesAr: 'لإرخاء مفاصل الورك قبل التمرين',
  },
  {
    id: 'warmup_leg_swings',
    name: 'Leg Swings',
    nameAr: 'تأرجح الساق',
    category: 'Warm-Up',
    categoryAr: 'الإحماء',
    sets: '1', reps: '15 each leg', rest: '0', restAr: '0 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=naW8u72lOzI',
    notes: 'Hold a wall for balance, swing leg forward and back',
    notesAr: 'أمسكي الحائط للتوازن، أرجحي الساق للأمام والخلف',
  },
  {
    id: 'warmup_jumping_jacks',
    name: 'Jumping Jacks',
    nameAr: 'القفز النجمي',
    category: 'Warm-Up',
    categoryAr: 'الإحماء',
    sets: '2', reps: '30 seconds', rest: '15', restAr: '15 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=c4DAnQ6DtF8',
    notes: 'Get heart rate up and warm the whole body',
    notesAr: 'لرفع معدل ضربات القلب وتدفئة الجسم كله',
  },
  {
    id: 'warmup_high_knees',
    name: 'High Knees',
    nameAr: 'رفع الركبتين',
    category: 'Warm-Up',
    categoryAr: 'الإحماء',
    sets: '2', reps: '30 seconds', rest: '15', restAr: '15 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=QgClj9UxWcQ',
    notes: 'Drive knees up to hip height, stay light on feet',
    notesAr: 'ارفعي الركبتين إلى مستوى الورك، ابقي خفيفة على قدميك',
  },

  // ── STRETCHING & RECOVERY ──
  {
    id: 'stretch_quad',
    name: 'Standing Quad Stretch',
    nameAr: 'إطالة الفخذ الأمامي',
    category: 'Stretching',
    categoryAr: 'الإطالة',
    sets: '1', reps: '30 sec each leg', rest: '0', restAr: '0 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=2hKbghN2fUE',
    notes: 'Hold ankle, stand tall, feel stretch in front of thigh',
    notesAr: 'أمسكي الكاحل، قفي منتصبة، أحسي بالشد في مقدمة الفخذ',
  },
  {
    id: 'stretch_hamstring',
    name: 'Seated Hamstring Stretch',
    nameAr: 'إطالة الفخذ الخلفي',
    category: 'Stretching',
    categoryAr: 'الإطالة',
    sets: '1', reps: '30 sec each leg', rest: '0', restAr: '0 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=wr_8aak4Wbc',
    notes: 'Sit on floor, extend one leg, reach toward foot',
    notesAr: 'اجلسي على الأرض، مدي ساقاً واحدة، امتدي نحو القدم',
  },
  {
    id: 'stretch_hip_flexor',
    name: 'Hip Flexor Stretch',
    nameAr: 'إطالة عضلة الورك الأمامية',
    category: 'Stretching',
    categoryAr: 'الإطالة',
    sets: '1', reps: '30 sec each side', rest: '0', restAr: '0 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=iZ1eZBY4fwM',
    notes: 'Lunge position, push hips forward gently',
    notesAr: 'وضعية الطعنة، ادفعي الورك للأمام بلطف',
  },
  {
    id: 'stretch_chest',
    name: 'Chest Opener Stretch',
    nameAr: 'إطالة الصدر',
    category: 'Stretching',
    categoryAr: 'الإطالة',
    sets: '1', reps: '30 seconds', rest: '0', restAr: '0 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=M850sCj9LHQ',
    notes: 'Clasp hands behind back, open chest upward',
    notesAr: 'شبكي يديك خلف ظهرك، افتحي الصدر للأعلى',
  },
  {
    id: 'stretch_shoulder',
    name: 'Cross-Body Shoulder Stretch',
    nameAr: 'إطالة الكتف',
    category: 'Stretching',
    categoryAr: 'الإطالة',
    sets: '1', reps: '30 sec each arm', rest: '0', restAr: '0 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=-1K0m5ywRcY',
    notes: 'Pull arm across chest, feel stretch in shoulder',
    notesAr: 'اسحبي الذراع عبر الصدر، أحسي بالشد في الكتف',
  },
  {
    id: 'stretch_child_pose',
    name: "Child's Pose",
    nameAr: 'وضعية الطفل',
    category: 'Stretching',
    categoryAr: 'الإطالة',
    sets: '1', reps: '60 seconds', rest: '0', restAr: '0 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=eqVMAPM00DM',
    notes: 'Kneel and reach arms forward, breathe deeply',
    notesAr: 'اركعي ومدي ذراعيك للأمام، تنفسي بعمق',
  },

  // ── HOME WORKOUTS ──
  {
    id: 'home_pushup',
    name: 'Push-Up',
    nameAr: 'تمرين الضغط',
    category: 'Home Workouts',
    categoryAr: 'تمارين المنزل',
    sets: '3', reps: '10–15', rest: '60', restAr: '60 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    notes: 'Keep body straight, lower chest to floor',
    notesAr: 'أبقي جسمك مستقيماً، انزلي حتى يلمس الصدر الأرض',
  },
  {
    id: 'home_squat',
    name: 'Bodyweight Squat',
    nameAr: 'سكوات بوزن الجسم',
    category: 'Home Workouts',
    categoryAr: 'تمارين المنزل',
    sets: '3', reps: '15–20', rest: '45', restAr: '45 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=aclHkVaku9U',
    notes: 'Feet shoulder-width, lower until thighs parallel',
    notesAr: 'قدماك بعرض الكتفين، انزلي حتى تتوازى الفخذان',
  },
  {
    id: 'home_lunge',
    name: 'Reverse Lunge',
    nameAr: 'الطعنة العكسية',
    category: 'Home Workouts',
    categoryAr: 'تمارين المنزل',
    sets: '3', reps: '12 each leg', rest: '45', restAr: '45 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=R-g5yPNYv2k',
    notes: 'Step back, lower knee toward floor, keep torso upright',
    notesAr: 'خطوي للخلف، انزلي الركبة نحو الأرض، أبقي الجذع منتصباً',
  },
  {
    id: 'home_glute_bridge',
    name: 'Glute Bridge',
    nameAr: 'جسر الأرداف',
    category: 'Home Workouts',
    categoryAr: 'تمارين المنزل',
    sets: '3', reps: '20', rest: '30', restAr: '30 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=OUgsJ8-Vi0E',
    notes: 'Lie on back, drive hips up, squeeze glutes at top',
    notesAr: 'استلقي على ظهرك، ارفعي الورك، اضغطي الأرداف في الأعلى',
  },
  {
    id: 'home_plank',
    name: 'Plank Hold',
    nameAr: 'تمرين البلانك',
    category: 'Home Workouts',
    categoryAr: 'تمارين المنزل',
    sets: '3', reps: '30–45 seconds', rest: '30', restAr: '30 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=pSHjTRCQxIw',
    notes: 'Straight line from head to heels, engage core',
    notesAr: 'خط مستقيم من الرأس إلى الكعب، شدي عضلات الكور',
  },
  {
    id: 'home_mountain_climbers',
    name: 'Mountain Climbers',
    nameAr: 'تسلق الجبل',
    category: 'Home Workouts',
    categoryAr: 'تمارين المنزل',
    sets: '3', reps: '30 seconds', rest: '30', restAr: '30 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=nmwgirgXLYM',
    notes: 'Drive knees to chest alternately, keep hips level',
    notesAr: 'أحضري الركبتين بالتناوب نحو الصدر، أبقي الورك مستوياً',
  },

  // ── PILATES ──
  {
    id: 'pilates_hundred',
    name: 'Pilates Hundred',
    nameAr: 'تمرين المئة (Hundred)',
    category: 'Pilates',
    categoryAr: 'البيلاتس',
    sets: '1', reps: '100 pumps', rest: '30', restAr: '30 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=9mlone4NObI',
    notes: 'Legs at 45°, pump arms 5 in + 5 out, breathe rhythmically',
    notesAr: 'الساقان بزاوية 45°، حركات الذراعين 5 داخل + 5 خارج، تنفس إيقاعي',
  },
  {
    id: 'pilates_roll_up',
    name: 'Pilates Roll Up',
    nameAr: 'الطرح للأمام (Roll Up)',
    category: 'Pilates',
    categoryAr: 'البيلاتس',
    sets: '3', reps: '8', rest: '30', restAr: '30 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=PGnibcCcAUE',
    notes: 'Peel spine off floor slowly, control the descent',
    notesAr: 'قشري العمود الفقري عن الأرض ببطء، تحكمي في النزول',
  },
  {
    id: 'pilates_single_leg_stretch',
    name: 'Single Leg Stretch',
    nameAr: 'إطالة ساق واحدة',
    category: 'Pilates',
    categoryAr: 'البيلاتس',
    sets: '3', reps: '10 each leg', rest: '20', restAr: '20 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=Ad4lgW4ieAM',
    notes: 'Alternate legs, keep shoulders off mat',
    notesAr: 'بدّلي الساقين، أبقي الكتفين مرفوعتين عن الحصيرة',
  },
  {
    id: 'pilates_double_leg_stretch',
    name: 'Double Leg Stretch',
    nameAr: 'إطالة الساقين معاً',
    category: 'Pilates',
    categoryAr: 'البيلاتس',
    sets: '3', reps: '10', rest: '20', restAr: '20 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=fuwzt4d7FuY',
    notes: 'Inhale extend, exhale pull in, keep lower back flat',
    notesAr: 'شهيق مع المد، زفير مع السحب، أبقي أسفل الظهر مسطحاً',
  },
  {
    id: 'pilates_spine_stretch',
    name: 'Spine Stretch Forward',
    nameAr: 'إطالة العمود الفقري للأمام',
    category: 'Pilates',
    categoryAr: 'البيلاتس',
    sets: '3', reps: '8', rest: '20', restAr: '20 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=140RTNMciH8',
    notes: 'Sit tall, reach forward, scoop belly in',
    notesAr: 'اجلسي منتصبة، امتدي للأمام، اسحبي البطن للداخل',
  },
  {
    id: 'pilates_swan',
    name: 'Swan Dive',
    nameAr: 'وضعية البجعة',
    category: 'Pilates',
    categoryAr: 'البيلاتس',
    sets: '3', reps: '8', rest: '20', restAr: '20 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=lslSedpC23Y',
    notes: 'Lie face down, lift chest using back muscles',
    notesAr: 'استلقي على بطنك، ارفعي الصدر باستخدام عضلات الظهر',
  },

  // ── MOBILITY & FLEXIBILITY ──
  {
    id: 'mob_thoracic_rotation',
    name: 'Thoracic Rotation',
    nameAr: 'دوران الصدر',
    category: 'Mobility',
    categoryAr: 'الحركة والمرونة',
    sets: '2', reps: '10 each side', rest: '20', restAr: '20 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=hhvHpsxKjXw',
    notes: 'On all fours, rotate upper spine, follow hand with eyes',
    notesAr: 'على الأربع، أدوري العمود الفقري العلوي، تابعي اليد بعينيك',
  },
  {
    id: 'mob_hip_90_90',
    name: 'Hip 90/90 Stretch',
    nameAr: 'إطالة الورك 90/90',
    category: 'Mobility',
    categoryAr: 'الحركة والمرونة',
    sets: '2', reps: '60 sec each side', rest: '20', restAr: '20 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=t4Zz6-aG8Iw',
    notes: 'Sit with both legs at 90°, lean over front leg',
    notesAr: 'اجلسي مع كلتا الساقين بزاوية 90°، انحني فوق الساق الأمامية',
  },
  {
    id: 'mob_ankle_circles',
    name: 'Ankle Circles',
    nameAr: 'دوران الكاحل',
    category: 'Mobility',
    categoryAr: 'الحركة والمرونة',
    sets: '2', reps: '10 each direction', rest: '0', restAr: '0 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=mzTQGYGI0Ng',
    notes: 'Improve ankle mobility and prevent injury',
    notesAr: 'لتحسين مرونة الكاحل والوقاية من الإصابات',
  },
  {
    id: 'mob_cat_cow',
    name: 'Cat-Cow Stretch',
    nameAr: 'تمرين القطة والبقرة',
    category: 'Mobility',
    categoryAr: 'الحركة والمرونة',
    sets: '2', reps: '10 cycles', rest: '20', restAr: '20 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=kqnua4rHVVA',
    notes: 'Breathe in on cow, breathe out on cat',
    notesAr: 'شهيق في وضعية البقرة، زفير في وضعية القطة',
  },
  {
    id: 'mob_world_greatest',
    name: "World's Greatest Stretch",
    nameAr: 'أعظم إطالة في العالم',
    category: 'Mobility',
    categoryAr: 'الحركة والمرونة',
    sets: '2', reps: '5 each side', rest: '20', restAr: '20 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=-CiWQ2IvY34',
    notes: 'Combines hip flexor, thoracic, and hamstring stretch',
    notesAr: 'يجمع إطالة الورك والصدر والفخذ الخلفي',
  },
  {
    id: 'mob_pigeon_pose',
    name: 'Pigeon Pose',
    nameAr: 'وضعية الحمامة',
    category: 'Mobility',
    categoryAr: 'الحركة والمرونة',
    sets: '1', reps: '60 sec each side', rest: '10', restAr: '10 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=0_zPqA65Nok',
    notes: 'Deep hip opener, breathe and relax into the stretch',
    notesAr: 'فتح عميق للورك، تنفسي واسترخي في الإطالة',
  },

  // ── QUICK WORKOUTS ──
  {
    id: 'quick_burpees',
    name: 'Burpees',
    nameAr: 'تمرين البيربي',
    category: 'Quick Workouts',
    categoryAr: 'تمارين سريعة',
    sets: '3', reps: '10', rest: '30', restAr: '30 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=BqWQkblauo8',
    notes: 'Full body explosive movement, modify by stepping instead of jumping',
    notesAr: 'حركة انفجارية لكامل الجسم، يمكن التعديل بالخطو بدلاً من القفز',
  },
  {
    id: 'quick_jumping_jacks',
    name: 'Jumping Jacks',
    nameAr: 'القفز النجمي',
    category: 'Quick Workouts',
    categoryAr: 'تمارين سريعة',
    sets: '3', reps: '30 seconds', rest: '15', restAr: '15 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=c4DAnQ6DtF8',
    notes: 'Keep a steady pace, land softly',
    notesAr: 'حافظي على وتيرة ثابتة، اهبطي بلطف',
  },
  {
    id: 'quick_high_knees',
    name: 'High Knees',
    nameAr: 'رفع الركبتين',
    category: 'Quick Workouts',
    categoryAr: 'تمارين سريعة',
    sets: '3', reps: '30 seconds', rest: '15', restAr: '15 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=QgClj9UxWcQ',
    notes: 'Drive knees up, pump arms, stay on balls of feet',
    notesAr: 'ارفعي الركبتين، حركي الذراعين، ابقي على مقدمة القدمين',
  },
  {
    id: 'quick_squat_jumps',
    name: 'Jump Squats',
    nameAr: 'سكوات القفز',
    category: 'Quick Workouts',
    categoryAr: 'تمارين سريعة',
    sets: '3', reps: '12', rest: '30', restAr: '30 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=CVaEhXotL7M',
    notes: 'Squat deep then explode upward, land softly',
    notesAr: 'انزلي عميقاً ثم اقفزي للأعلى بقوة، اهبطي بلطف',
  },
  {
    id: 'quick_pushup',
    name: 'Push-Up',
    nameAr: 'تمرين الضغط',
    category: 'Quick Workouts',
    categoryAr: 'تمارين سريعة',
    sets: '3', reps: '12', rest: '30', restAr: '30 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=IODxDxX7oi4',
    notes: 'Keep core tight, full range of motion',
    notesAr: 'أبقي الكور مشدوداً، نطاق حركة كامل',
  },
  {
    id: 'quick_plank',
    name: 'Plank Hold',
    nameAr: 'تمرين البلانك',
    category: 'Quick Workouts',
    categoryAr: 'تمارين سريعة',
    sets: '3', reps: '30 seconds', rest: '20', restAr: '20 ثانية',
    youtubeUrl: 'https://www.youtube.com/watch?v=pSHjTRCQxIw',
    notes: 'Straight body line, breathe steadily',
    notesAr: 'خط جسم مستقيم، تنفسي بانتظام',
  },
];

// ── UPDATED getProgramByGender to include new categories ──
export function getExercisesByCategoryAll(
  gender: "male" | "female"
): Record<string, Exercise[]> {
  const program = getProgramByGender(gender);
  const grouped: Record<string, Exercise[]> = {};
  for (const ex of program.exercises) {
    if (!grouped[ex.category]) grouped[ex.category] = [];
    grouped[ex.category].push(ex);
  }
  // Add new category exercises (shared for all genders)
  for (const ex of newCategoryExercises) {
    if (!grouped[ex.category]) grouped[ex.category] = [];
    grouped[ex.category].push(ex);
  }
  return grouped;
}
