// Prime Fit — Exercise Library
// Gender-specific exercise programs with YouTube tutorial links

export interface Exercise {
  id: string;
  name: string;
  nameAr: string;
  category: string;
  categoryAr: string;
  sets: string;
  reps: string;
  rest: string; // in seconds
  restAr: string;
  youtubeUrl: string;
  imageUrl?: string;
  notes?: string;
  notesAr?: string;
}

export interface GenderProgram {
  goal: string;
  goalAr: string;
  schedule: string;
  scheduleAr: string;
  restBetweenSets: string;
  restBetweenSetsAr: string;
  tips: string[];
  tipsAr: string[];
  weeklyPlan: string[];
  weeklyPlanAr: string[];
  exercises: Exercise[];
}

// ── WOMEN'S PROGRAM ──────────────────────────────────────────────────────────
export const womenProgram: GenderProgram = {
  goal: "Tone the body, build balanced feminine muscles, and improve fitness.",
  goalAr: "شد الجسم، بناء عضلات أنثوية متناسقة، وتحسين اللياقة.",
  schedule: "3–5 days per week",
  scheduleAr: "3–5 أيام بالأسبوع",
  restBetweenSets: "45–90 seconds depending on exercise intensity",
  restBetweenSetsAr: "45–90 ثانية حسب شدة التمرين",
  tips: [
    "Always start with 5–10 minutes of cardio warm-up.",
    "Focus on slow movement and weight control.",
    "Gradually increase weights over time.",
    "Sleep and nutrition are essential for visible results.",
    "Split your workouts: Upper day / Lower + Glutes day / Back + Core day / Rest or Cardio.",
  ],
  tipsAr: [
    "ابدئي دائمًا بـ 5–10 دقائق إحماء كارديو.",
    "ركزي على الحركة البطيئة والتحكم بالوزن.",
    "زيدي الأوزان تدريجيًا مع الوقت.",
    "النوم والتغذية مهمين جدًا لظهور النتائج.",
    "يمكن تقسيم التمارين: يوم علوي / يوم سفلي + أرداف / يوم ظهر + بطن / يوم راحة أو كارديو.",
  ],
  weeklyPlan: [
    "Day 1: Upper Body (Shoulders + Chest + Arms)",
    "Day 2: Lower Body + Glutes",
    "Day 3: Back + Core",
    "Day 4: Rest or Light Cardio",
    "Day 5: Repeat cycle",
  ],
  weeklyPlanAr: [
    "اليوم 1: جزء علوي (أكتاف + صدر + ذراع)",
    "اليوم 2: جزء سفلي + أرداف",
    "اليوم 3: ظهر + بطن",
    "اليوم 4: راحة أو كارديو خفيف",
    "اليوم 5: تكرار الدورة",
  ],
  exercises: [
    // ── SHOULDERS ──
    {
      id: "w-shoulder-press",
      name: "Shoulder Press Machine",
      nameAr: "جهاز Shoulder Press",
      category: "Shoulders",
      categoryAr: "الأكتاف",
      sets: "4",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=qEwKCR5JCog",
      imageUrl: "/manus-storage/machine-shoulder-press_471161cb.png",
      notes: "Keep back straight, press upward smoothly",
      notesAr: "حافظي على استقامة الظهر، ادفعي للأعلى بسلاسة",
    },
    {
      id: "w-lateral-raise",
      name: "Lateral Raise Machine",
      nameAr: "جهاز Lateral Raise",
      category: "Shoulders",
      categoryAr: "الأكتاف",
      sets: "3",
      reps: "12–15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=3VcKaXpzqRo",
      imageUrl: "/manus-storage/machine-lateral-raise_e9f5c24a.png",
      notes: "Raise arms to shoulder height, controlled movement",
      notesAr: "ارفعي الذراعين لمستوى الكتف، حركة متحكمة",
    },
    // ── CHEST ──
    {
      id: "w-chest-press",
      name: "Chest Press Machine",
      nameAr: "جهاز Chest Press",
      category: "Chest",
      categoryAr: "الصدر",
      sets: "4",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=xUm0BiZCX_I",
      imageUrl: "/manus-storage/machine-chest-press_82846c6c.jpg",
      notes: "Squeeze chest at the top of movement",
      notesAr: "اضغطي عضلة الصدر عند نهاية الحركة",
    },
    {
      id: "w-pec-deck",
      name: "Pec Deck Machine",
      nameAr: "جهاز Pec Deck (تفتيح صدر)",
      category: "Chest",
      categoryAr: "الصدر",
      sets: "3",
      reps: "12–15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=Z57CtFmRMxA",
      imageUrl: "/manus-storage/machine-pec-deck_585db15a.jpg",
      notes: "Controlled arc motion, feel the stretch",
      notesAr: "حركة قوسية متحكمة، أحسسي بالشد",
    },
    // ── ARMS ──
    {
      id: "w-biceps-curl",
      name: "Biceps Curl Machine",
      nameAr: "جهاز Biceps Curl",
      category: "Arms",
      categoryAr: "الذراع",
      sets: "3",
      reps: "12",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=ykJmrZ5v0Oo",
      imageUrl: "/manus-storage/machine-bicep-curl_0cb63636.jpg",
      notes: "Full range of motion, squeeze at top",
      notesAr: "نطاق حركة كامل، اضغطي في الأعلى",
    },
    {
      id: "w-triceps-pushdown",
      name: "Triceps Pushdown Machine",
      nameAr: "جهاز Triceps Pushdown",
      category: "Arms",
      categoryAr: "الذراع",
      sets: "3",
      reps: "12–15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=2-LAMcpzODU",
      imageUrl: "/manus-storage/machine-bicep-curl_0cb63636.jpg",
      notes: "Keep elbows close to body",
      notesAr: "أبقي المرفقين قريبين من الجسم",
    },
    // ── BACK ──
    {
      id: "w-lat-pulldown",
      name: "Lat Pulldown Machine",
      nameAr: "جهاز Lat Pulldown",
      category: "Back",
      categoryAr: "الظهر",
      sets: "4",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=CAwf7n6Luuc",
      imageUrl: "/manus-storage/machine-lat-pulldown_0cc3f20a.jpg",
      notes: "Pull to upper chest, squeeze shoulder blades",
      notesAr: "اسحبي لأعلى الصدر، اضغطي لوحي الكتف",
    },
    {
      id: "w-seated-row",
      name: "Seated Row Machine",
      nameAr: "جهاز Seated Row",
      category: "Back",
      categoryAr: "الظهر",
      sets: "4",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=GZbfZ033f74",
      imageUrl: "/manus-storage/machine-seated-row_95d26900.jpg",
      notes: "Pull elbows back, squeeze back muscles",
      notesAr: "اسحبي المرفقين للخلف، اضغطي عضلات الظهر",
    },
    {
      id: "w-back-extension",
      name: "Back Extension Machine",
      nameAr: "جهاز Back Extension",
      category: "Back",
      categoryAr: "الظهر",
      sets: "3",
      reps: "15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=ph3pddpKzzw",
      imageUrl: "/manus-storage/machine-back-extension_c32dec11.jpg",
      notes: "Controlled movement, don't hyperextend",
      notesAr: "حركة متحكمة، لا تبالغي في التمديد",
    },
    // ── CORE ──
    {
      id: "w-ab-crunch",
      name: "Ab Crunch Machine",
      nameAr: "جهاز Ab Crunch",
      category: "Core",
      categoryAr: "منطقة البطن",
      sets: "4",
      reps: "15–20",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=MKmrqcoCZ-M",
      notes: "Exhale on the crunch, slow return",
      notesAr: "ازفري عند الانقباض، عودة بطيئة",
    },
    {
      id: "w-cable-crunch",
      name: "Cable Crunch",
      nameAr: "جهاز Cable Crunch",
      category: "Core",
      categoryAr: "منطقة البطن",
      sets: "3",
      reps: "15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=2fbujeH3F0E",
      notes: "Round the back, focus on abs contraction",
      notesAr: "قوسي الظهر، ركزي على انقباض البطن",
    },
    {
      id: "w-captain-chair",
      name: "Captain Chair Leg Raise",
      nameAr: "رفع الأرجل على جهاز Captain Chair",
      category: "Core",
      categoryAr: "منطقة البطن",
      sets: "3",
      reps: "12–15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=p7j02V1fIzk",
      notes: "Controlled leg raise, no swinging",
      notesAr: "رفع الأرجل بتحكم، بدون تأرجح",
    },
    // ── GLUTES ──
    {
      id: "w-hip-thrust",
      name: "Hip Thrust Machine",
      nameAr: "جهاز Hip Thrust",
      category: "Glutes",
      categoryAr: "الأرداف",
      sets: "4",
      reps: "10–12",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=SEdqd1n0cvg",
      notes: "Squeeze glutes at the top, full hip extension",
      notesAr: "اضغطي الأرداف في الأعلى، تمديد كامل للورك",
    },
    {
      id: "w-glute-kickback",
      name: "Glute Kickback Machine",
      nameAr: "جهاز Glute Kickback",
      category: "Glutes",
      categoryAr: "الأرداف",
      sets: "4",
      reps: "12–15 per leg",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=donIef4oMDQ",
      notes: "Squeeze glute at peak, slow return",
      notesAr: "اضغطي الردف في الذروة، عودة بطيئة",
    },
    {
      id: "w-hip-abductor",
      name: "Hip Abductor Machine",
      nameAr: "جهاز Hip Abductor",
      category: "Glutes",
      categoryAr: "الأرداف",
      sets: "4",
      reps: "15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=Ep-e2HRt5vU",
      notes: "Slow controlled outward movement",
      notesAr: "حركة خارجية بطيئة ومتحكمة",
    },
    // ── LEGS ──
    {
      id: "w-leg-press",
      name: "Leg Press Machine",
      nameAr: "جهاز Leg Press",
      category: "Legs",
      categoryAr: "الساق",
      sets: "4",
      reps: "10–12",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
      imageUrl: "/manus-storage/machine-leg-press_59da16cc.jpg",
      notes: "Don't lock knees at top, controlled descent",
      notesAr: "لا تقفلي الركبتين في الأعلى، نزول متحكم",
    },
    {
      id: "w-leg-extension",
      name: "Leg Extension Machine",
      nameAr: "جهاز Leg Extension",
      category: "Legs",
      categoryAr: "الساق",
      sets: "3",
      reps: "12–15",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=YyvSfVjQeL0",
      imageUrl: "/manus-storage/machine-leg-extension_74a07b5a.jpg",
      notes: "Full extension, squeeze quads at top",
      notesAr: "تمديد كامل، اضغطي عضلة الفخذ في الأعلى",
    },
    {
      id: "w-leg-curl",
      name: "Leg Curl Machine",
      nameAr: "جهاز Leg Curl",
      category: "Legs",
      categoryAr: "الساق",
      sets: "3",
      reps: "12–15",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=1Tq3QdYUuHs",
      imageUrl: "/manus-storage/machine-leg-curl_52a73a8d.jpg",
      notes: "Slow controlled curl, full range",
      notesAr: "ثني بطيء ومتحكم، نطاق كامل",
    },
    {
      id: "w-calf-raise",
      name: "Calf Raise Machine",
      nameAr: "جهاز Calf Raise",
      category: "Legs",
      categoryAr: "الساق",
      sets: "4",
      reps: "15–20",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=-M4-G8p1fCI",
      imageUrl: "/manus-storage/machine-calf-raise_56717650.jpg",
      notes: "Full range, pause at top and bottom",
      notesAr: "نطاق كامل، توقف في الأعلى والأسفل",
    },
  ],
};

// ── MEN'S PROGRAM ────────────────────────────────────────────────────────────
export const menProgram: GenderProgram = {
  goal: "Build muscle, increase strength, and improve muscular symmetry.",
  goalAr: "بناء عضلات، زيادة القوة، وتحسين التناسق العضلي.",
  schedule: "4–6 days per week",
  scheduleAr: "4–6 أيام بالأسبوع",
  restBetweenSets: "Heavy: 90–120s | Medium: 60–90s | Isolation: 45–60s",
  restBetweenSetsAr: "تمارين ثقيلة: 90–120 ث | متوسطة: 60–90 ث | عزل: 45–60 ث",
  tips: [
    "Focus on correct form before increasing weight.",
    "Try to increase weight or reps progressively each week.",
    "Protein and sleep are essential for muscle building.",
    "Cardio 2–3 times per week helps fitness and definition.",
    "Never skip leg day — it's key for full muscular balance.",
  ],
  tipsAr: [
    "ركز على الأداء الصحيح قبل زيادة الوزن.",
    "حاول زيادة الوزن أو التكرارات تدريجيًا أسبوعيًا.",
    "البروتين والنوم أساسيان لبناء العضلات.",
    "الكارديو 2–3 مرات أسبوعيًا يساعد على اللياقة والتنشيف.",
    "لا تهمل تمارين الأرجل لتحقيق توازن عضلي كامل.",
  ],
  weeklyPlan: [
    "Day 1: Chest + Triceps",
    "Day 2: Back + Biceps",
    "Day 3: Rest",
    "Day 4: Shoulders + Core",
    "Day 5: Full Legs",
    "Day 6–7: Rest or Cardio",
  ],
  weeklyPlanAr: [
    "اليوم 1: صدر + ترايسبس",
    "اليوم 2: ظهر + بايسبس",
    "اليوم 3: راحة",
    "اليوم 4: أكتاف + بطن",
    "اليوم 5: أرجل كاملة",
    "اليوم 6–7: راحة أو كارديو",
  ],
  exercises: [
    // ── CHEST ──
    {
      id: "m-chest-press",
      name: "Chest Press Machine",
      nameAr: "جهاز Chest Press",
      category: "Chest",
      categoryAr: "الصدر",
      sets: "4",
      reps: "8–12",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=xUm0BiZCX_I",
      imageUrl: "/manus-storage/machine-chest-press_82846c6c.jpg",
      notes: "Full range, squeeze chest at top",
      notesAr: "نطاق كامل، اضغط عضلة الصدر في الأعلى",
    },
    {
      id: "m-incline-chest-press",
      name: "Incline Chest Press Machine",
      nameAr: "جهاز Incline Chest Press",
      category: "Chest",
      categoryAr: "الصدر",
      sets: "4",
      reps: "10",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=DbFgADa2PL8",
      notes: "Targets upper chest, controlled descent",
      notesAr: "يستهدف الصدر العلوي، نزول متحكم",
    },
    {
      id: "m-pec-deck",
      name: "Pec Deck Machine",
      nameAr: "جهاز Pec Deck",
      category: "Chest",
      categoryAr: "الصدر",
      sets: "3",
      reps: "12–15",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=Z57CtFmRMxA",
      imageUrl: "/manus-storage/machine-pec-deck_585db15a.jpg",
      notes: "Feel the stretch, controlled arc",
      notesAr: "أحس بالشد، قوس متحكم",
    },
    // ── BACK ──
    {
      id: "m-lat-pulldown",
      name: "Lat Pulldown Machine",
      nameAr: "جهاز Lat Pulldown",
      category: "Back",
      categoryAr: "الظهر",
      sets: "4",
      reps: "8–12",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=CAwf7n6Luuc",
      imageUrl: "/manus-storage/machine-lat-pulldown_0cc3f20a.jpg",
      notes: "Pull to upper chest, squeeze lats",
      notesAr: "اسحب لأعلى الصدر، اضغط العضلة الظهرية",
    },
    {
      id: "m-seated-row",
      name: "Seated Row Machine",
      nameAr: "جهاز Seated Row",
      category: "Back",
      categoryAr: "الظهر",
      sets: "4",
      reps: "10–12",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=GZbfZ033f74",
      imageUrl: "/manus-storage/machine-seated-row_95d26900.jpg",
      notes: "Pull elbows back, full contraction",
      notesAr: "اسحب المرفقين للخلف، انقباض كامل",
    },
    {
      id: "m-hammer-row",
      name: "Hammer Row Machine",
      nameAr: "جهاز Hammer Row",
      category: "Back",
      categoryAr: "الظهر",
      sets: "3",
      reps: "10",
      rest: "75",
      restAr: "75 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=roCP0_FEWGI",
      notes: "Neutral grip, retract shoulder blades",
      notesAr: "قبضة محايدة، اسحب لوحي الكتف للخلف",
    },
    {
      id: "m-back-extension",
      name: "Back Extension Machine",
      nameAr: "جهاز Back Extension",
      category: "Back",
      categoryAr: "الظهر",
      sets: "3",
      reps: "15",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=ph3pddpKzzw",
      imageUrl: "/manus-storage/machine-back-extension_c32dec11.jpg",
      notes: "Controlled, don't hyperextend",
      notesAr: "متحكم، لا تبالغ في التمديد",
    },
    // ── SHOULDERS ──
    {
      id: "m-shoulder-press",
      name: "Shoulder Press Machine",
      nameAr: "جهاز Shoulder Press",
      category: "Shoulders",
      categoryAr: "الأكتاف",
      sets: "4",
      reps: "10",
      rest: "75",
      restAr: "75 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=qEwKCR5JCog",
      imageUrl: "/manus-storage/machine-shoulder-press_471161cb.png",
      notes: "Press overhead, don't shrug",
      notesAr: "ادفع للأعلى، لا ترفع الكتفين",
    },
    {
      id: "m-lateral-raise",
      name: "Lateral Raise Machine",
      nameAr: "جهاز Lateral Raise",
      category: "Shoulders",
      categoryAr: "الأكتاف",
      sets: "4",
      reps: "12–15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=3VcKaXpzqRo",
      imageUrl: "/manus-storage/machine-lateral-raise_e9f5c24a.png",
      notes: "Lead with elbows, raise to shoulder height",
      notesAr: "قُد بالمرفقين، ارفع لمستوى الكتف",
    },
    {
      id: "m-rear-delt-fly",
      name: "Rear Delt Fly Machine",
      nameAr: "جهاز Rear Delt Fly",
      category: "Shoulders",
      categoryAr: "الأكتاف",
      sets: "3",
      reps: "12–15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=EA7u4Q_8HQ0",
      imageUrl: "/manus-storage/machine-rear-delt_3d456993.webp",
      notes: "Squeeze rear delts, slow return",
      notesAr: "اضغط الكتف الخلفي، عودة بطيئة",
    },
    // ── ARMS ──
    {
      id: "m-biceps-curl",
      name: "Biceps Curl Machine",
      nameAr: "جهاز Biceps Curl",
      category: "Arms",
      categoryAr: "الذراع",
      sets: "4",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=ykJmrZ5v0Oo",
      imageUrl: "/manus-storage/machine-bicep-curl_0cb63636.jpg",
      notes: "Full range, peak contraction at top",
      notesAr: "نطاق كامل، انقباض قمة في الأعلى",
    },
    {
      id: "m-preacher-curl",
      name: "Preacher Curl Machine",
      nameAr: "جهاز Preacher Curl",
      category: "Arms",
      categoryAr: "الذراع",
      sets: "3",
      reps: "12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=fIWP-FRFNU0",
      imageUrl: "/manus-storage/machine-bicep-curl_0cb63636.jpg",
      notes: "Isolates biceps, controlled negative",
      notesAr: "يعزل البايسبس، نزول متحكم",
    },
    {
      id: "m-triceps-pushdown",
      name: "Triceps Pushdown Machine",
      nameAr: "جهاز Triceps Pushdown",
      category: "Arms",
      categoryAr: "الذراع",
      sets: "4",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=2-LAMcpzODU",
      imageUrl: "/manus-storage/machine-bicep-curl_0cb63636.jpg",
      notes: "Keep elbows fixed, full extension",
      notesAr: "أبقِ المرفقين ثابتين، تمديد كامل",
    },
    {
      id: "m-dip-machine",
      name: "Dip Machine",
      nameAr: "جهاز Dip Machine",
      category: "Arms",
      categoryAr: "الذراع",
      sets: "3",
      reps: "10–12",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=wjUmnZH528Y",
      imageUrl: "/manus-storage/machine-bicep-curl_0cb63636.jpg",
      notes: "Lean slightly forward for chest focus",
      notesAr: "انحنِ للأمام قليلاً للتركيز على الصدر",
    },
    // ── CORE ──
    {
      id: "m-ab-crunch",
      name: "Ab Crunch Machine",
      nameAr: "جهاز Ab Crunch",
      category: "Core",
      categoryAr: "البطن",
      sets: "4",
      reps: "15–20",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=MKmrqcoCZ-M",
      notes: "Exhale on crunch, slow return",
      notesAr: "ازفر عند الانقباض، عودة بطيئة",
    },
    {
      id: "m-cable-crunch",
      name: "Cable Crunch",
      nameAr: "جهاز Cable Crunch",
      category: "Core",
      categoryAr: "البطن",
      sets: "4",
      reps: "15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=2fbujeH3F0E",
      notes: "Round the back, abs do the work",
      notesAr: "قوس الظهر، البطن يقوم بالعمل",
    },
    {
      id: "m-leg-raise",
      name: "Hanging Leg Raise",
      nameAr: "رفع الأرجل",
      category: "Core",
      categoryAr: "البطن",
      sets: "3",
      reps: "15",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=hdng3Nm1x_E",
      notes: "Controlled raise, no swinging",
      notesAr: "رفع متحكم، بدون تأرجح",
    },
    // ── LEGS ──
    {
      id: "m-leg-press",
      name: "Leg Press Machine",
      nameAr: "جهاز Leg Press",
      category: "Legs",
      categoryAr: "الساق والأرداف",
      sets: "4",
      reps: "10–12",
      rest: "90",
      restAr: "90 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=IZxyjW7MPJQ",
      imageUrl: "/manus-storage/machine-leg-press_59da16cc.jpg",
      notes: "Don't lock knees, full depth",
      notesAr: "لا تقفل الركبتين، عمق كامل",
    },
    {
      id: "m-squat-machine",
      name: "Squat Machine (Smith/Hack)",
      nameAr: "جهاز Squat Machine",
      category: "Legs",
      categoryAr: "الساق والأرداف",
      sets: "4",
      reps: "8–10",
      rest: "120",
      restAr: "120 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=U3HlEF_E9fo",
      imageUrl: "/manus-storage/machine-leg-press_59da16cc.jpg",
      notes: "Deep squat, chest up, knees track toes",
      notesAr: "سكوات عميق، صدر للأعلى، ركبتان تتبعان القدمين",
    },
    {
      id: "m-leg-extension",
      name: "Leg Extension Machine",
      nameAr: "جهاز Leg Extension",
      category: "Legs",
      categoryAr: "الساق والأرداف",
      sets: "4",
      reps: "12–15",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=YyvSfVjQeL0",
      imageUrl: "/manus-storage/machine-leg-extension_74a07b5a.jpg",
      notes: "Squeeze quads at full extension",
      notesAr: "اضغط عضلة الفخذ عند التمديد الكامل",
    },
    {
      id: "m-leg-curl",
      name: "Leg Curl Machine",
      nameAr: "جهاز Leg Curl",
      category: "Legs",
      categoryAr: "الساق والأرداف",
      sets: "4",
      reps: "12–15",
      rest: "60",
      restAr: "60 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=1Tq3QdYUuHs",
      imageUrl: "/manus-storage/machine-leg-curl_52a73a8d.jpg",
      notes: "Full range, slow eccentric",
      notesAr: "نطاق كامل، نزول بطيء",
    },
    {
      id: "m-calf-raise",
      name: "Calf Raise Machine",
      nameAr: "جهاز Calf Raise",
      category: "Legs",
      categoryAr: "الساق والأرداف",
      sets: "5",
      reps: "15–20",
      rest: "45",
      restAr: "45 ثانية",
      youtubeUrl: "https://www.youtube.com/watch?v=-M4-G8p1fCI",
      imageUrl: "/manus-storage/machine-calf-raise_56717650.jpg",
      notes: "Full range, pause at top and bottom",
      notesAr: "نطاق كامل، توقف في الأعلى والأسفل",
    },
  ],
};

export function getProgramByGender(gender: "male" | "female"): GenderProgram {
  return gender === "female" ? womenProgram : menProgram;
}

export function getExercisesByCategory(
  gender: "male" | "female"
): Record<string, Exercise[]> {
  const program = getProgramByGender(gender);
  const grouped: Record<string, Exercise[]> = {};
  for (const ex of program.exercises) {
    if (!grouped[ex.category]) grouped[ex.category] = [];
    grouped[ex.category].push(ex);
  }
  return grouped;
}
