/**
 * WooCommerce Order Poller
 *
 * Runs every 3 minutes. Fetches orders with status "processing" or "completed"
 * from WooCommerce REST API, checks if a license was already issued,
 * and sends the key + email for any that were missed by the webhook.
 *
 * This is the reliable fallback — webhook fires instantly, this catches anything missed.
 */

import { ENV } from "../_core/env";
import { createAccessCode, getAccessCodeByOrderId } from "../db";
import { generateLicenseKey, detectPlan, planToExpiry, hasPrimeFitProduct } from "./licenseUtils";
import { sendLicenseEmail } from "../_core/email";
import crypto from "crypto";

const POLL_INTERVAL_MS     = 3 * 60 * 1000;
const LOOK_BACK_HOURS      = 24;




async function fetchRecentPaidOrders(): Promise<any[]> {
  if (!ENV.wooStoreUrl || !ENV.wooConsumerKey || !ENV.wooConsumerSecret) {
    console.warn("[WooPoller] WooCommerce credentials not configured — skipping poll");
    return [];
  }

  const after = new Date(Date.now() - LOOK_BACK_HOURS * 60 * 60 * 1000).toISOString();

  const params = new URLSearchParams({
    status:   "processing,completed",
    per_page: "50",
    after,
    orderby:  "date",
    order:    "desc",
  });

  const url  = `${ENV.wooStoreUrl.replace(/\/$/, "")}/wp-json/wc/v3/orders?${params}`;
  const auth = Buffer.from(`${ENV.wooConsumerKey}:${ENV.wooConsumerSecret}`).toString("base64");

  const res = await fetch(url, {
    headers: {
      Authorization: `Basic ${auth}`,
      "Content-Type": "application/json",
    },
  });

  if (!res.ok) {
    console.error(`[WooPoller] API error ${res.status}: ${await res.text()}`);
    return [];
  }

  return res.json();
}

async function processOrder(order: any): Promise<void> {
  const orderId: number = order.id;
  const status:  string = order.status;

  if (!["processing", "completed"].includes(status)) return;

  // Only issue licenses for Prime Fit product (ID: 5802)
  if (!hasPrimeFitProduct(order)) {
    console.log(`[WooPoller] Order #${orderId} skipped — no Prime Fit product`);
    return;
  }

  // Check if already issued
  let existing = null;
  try {
    existing = await getAccessCodeByOrderId(orderId);
  } catch {
    // orderId column may not exist yet — skip idempotency check
  }
  if (existing) return; // already handled

  const billing       = order.billing ?? {};
  const customerEmail = billing.email ?? "";
  const customerName  = [billing.first_name, billing.last_name].filter(Boolean).join(" ") || "Customer";

  if (!customerEmail) {
    console.warn(`[WooPoller] Order #${orderId} has no email — skipping`);
    return;
  }

  const licenseKey = generateLicenseKey();
  const plan       = detectPlan(order?.line_items ?? []);
  const expiresAt  = planToExpiry(plan);

  try {
    await createAccessCode({
      code: licenseKey, customerName, customerEmail,
      note: `Auto-generated by poller for WooCommerce order #${orderId} (${status}) [plan:${plan}]`,
      isActive: true, orderId, expiresAt,
    });
  } catch {
    await createAccessCode({
      code: licenseKey, customerName, customerEmail,
      note: `Auto-generated by poller for WooCommerce order #${orderId} (${status}) [plan:${plan}]`,
      isActive: true, expiresAt,
    });
  }

  const emailSent = await sendLicenseEmail({ to: customerEmail, customerName, licenseKey, orderNumber: orderId });
  console.log(`[WooPoller] ✅ Order #${orderId} → ${licenseKey} | email: ${emailSent} | ${customerEmail}`);
}

async function pollOrders(): Promise<void> {
  try {
    console.log("[WooPoller] Checking for undelivered paid orders...");
    const orders = await fetchRecentPaidOrders();
    console.log(`[WooPoller] Found ${orders.length} recent paid orders`);

    for (const order of orders) {
      try {
        await processOrder(order);
      } catch (err: any) {
        console.error(`[WooPoller] Error processing order #${order.id}:`, err.message);
      }
    }
  } catch (err: any) {
    console.error("[WooPoller] Poll failed:", err.message);
  }
}

export function startWooPoller(): void {
  if (!ENV.wooStoreUrl || !ENV.wooConsumerKey || !ENV.wooConsumerSecret) {
    console.warn("[WooPoller] Skipping — WOO_STORE_URL / WOO_CONSUMER_KEY / WOO_CONSUMER_SECRET not set");
    return;
  }

  console.log(`[WooPoller] Starting — polling every ${POLL_INTERVAL_MS / 60000} minutes`);

  // Run once immediately on startup, then every 3 minutes
  setTimeout(pollOrders, 10_000); // 10s after boot (let DB connect first)
  setInterval(pollOrders, POLL_INTERVAL_MS);
}
