/**
 * WooCommerce Order Poller
 *
 * Runs every 3 minutes. Fetches orders with status "processing" or "completed"
 * from WooCommerce REST API, checks if a license was already issued,
 * and sends the key + email for any that were missed by the webhook.
 *
 * This is the reliable fallback — webhook fires instantly, this catches anything missed.
 */

import { ENV } from "../_core/env";
import { createAccessCode, getAccessCodeByOrderId, listAccessCodes, toggleAccessCode } from "../db";
import { sendLicenseEmail } from "../_core/email";
import crypto from "crypto";

const POLL_INTERVAL_MS     = 3 * 60 * 1000;
const LOOK_BACK_HOURS      = 24;
const PRIME_FIT_PRODUCT_ID = 5802;

function generateLicenseKey(): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  const part  = () => Array.from({ length: 4 }, () =>
    chars[crypto.randomInt(0, chars.length)]
  ).join("");
  return `PRIME-${part()}-${part()}`;
}

async function fetchRecentPaidOrders(): Promise<any[]> {
  if (!ENV.wooStoreUrl || !ENV.wooConsumerKey || !ENV.wooConsumerSecret) {
    console.warn("[WooPoller] WooCommerce credentials not configured — skipping poll");
    return [];
  }

  const after = new Date(Date.now() - LOOK_BACK_HOURS * 60 * 60 * 1000).toISOString();

  const params = new URLSearchParams({
    status:   "processing,completed",
    per_page: "50",
    after,
    orderby:  "date",
    order:    "desc",
  });

  const url  = `${ENV.wooStoreUrl.replace(/\/$/, "")}/wp-json/wc/v3/orders?${params}`;
  const auth = Buffer.from(`${ENV.wooConsumerKey}:${ENV.wooConsumerSecret}`).toString("base64");

  const res = await fetch(url, {
    headers: {
      Authorization: `Basic ${auth}`,
      "Content-Type": "application/json",
    },
  });

  if (!res.ok) {
    console.error(`[WooPoller] API error ${res.status}: ${await res.text()}`);
    return [];
  }

  return res.json();
}

async function processOrder(order: any): Promise<void> {
  const orderId: number = order.id;
  const status:  string = order.status;

  if (!["processing", "completed"].includes(status)) return;

  // Only issue licenses for Prime Fit product (ID: 5802)
  const lineItems: any[] = order?.line_items ?? [];
  const hasPrimeFit = lineItems.some(
    (item) => item.product_id === PRIME_FIT_PRODUCT_ID || item.variation_id === PRIME_FIT_PRODUCT_ID
  );
  if (!hasPrimeFit) {
    console.log(`[WooPoller] Order #${orderId} skipped — no Prime Fit product`);
    return;
  }

  // Check if already issued
  let existing = null;
  try {
    existing = await getAccessCodeByOrderId(orderId);
  } catch {
    // orderId column may not exist yet — skip idempotency check
  }
  if (existing) return; // already handled

  const billing       = order.billing ?? {};
  const customerEmail = billing.email ?? "";
  const customerName  = [billing.first_name, billing.last_name].filter(Boolean).join(" ") || "Customer";

  if (!customerEmail) {
    console.warn(`[WooPoller] Order #${orderId} has no email — skipping`);
    return;
  }

  const licenseKey = generateLicenseKey();

  try {
    await createAccessCode({
      code:          licenseKey,
      customerName,
      customerEmail,
      note:          `Auto-generated by poller for WooCommerce order #${orderId} (${status})`,
      isActive:      true,
      orderId,
    });
  } catch {
    // orderId column missing — insert without it
    await createAccessCode({
      code:          licenseKey,
      customerName,
      customerEmail,
      note:          `Auto-generated by poller for WooCommerce order #${orderId} (${status}) — run migration 0006`,
      isActive:      true,
    });
  }

  const emailSent = await sendLicenseEmail({ to: customerEmail, customerName, licenseKey, orderNumber: orderId });
  console.log(`[WooPoller] ✅ Order #${orderId} → ${licenseKey} | email: ${emailSent} | ${customerEmail}`);
}

async function deactivateExpiredKeys(): Promise<void> {
  try {
    const all = await listAccessCodes();
    const now = new Date();
    let count = 0;
    for (const key of all) {
      if (key.isActive && key.expiresAt && new Date(key.expiresAt) < now) {
        await toggleAccessCode(key.id, false);
        count++;
        console.log(`[WooPoller] ⏰ Expired key deactivated: ${key.code} (expired ${key.expiresAt})`);
      }
    }
    if (count > 0) console.log(`[WooPoller] Deactivated ${count} expired license key(s)`);
  } catch (err: any) {
    console.error("[WooPoller] Error deactivating expired keys:", err.message);
  }
}

async function pollOrders(): Promise<void> {
  try {
    console.log("[WooPoller] Checking for undelivered paid orders...");
    const orders = await fetchRecentPaidOrders();
    console.log(`[WooPoller] Found ${orders.length} recent paid orders`);

    for (const order of orders) {
      try {
        await processOrder(order);
      } catch (err: any) {
        console.error(`[WooPoller] Error processing order #${order.id}:`, err.message);
      }
    }

    // Also sweep for expired keys on every poll
    await deactivateExpiredKeys();
  } catch (err: any) {
    console.error("[WooPoller] Poll failed:", err.message);
  }
}

export function startWooPoller(): void {
  if (!ENV.wooStoreUrl || !ENV.wooConsumerKey || !ENV.wooConsumerSecret) {
    console.warn("[WooPoller] Skipping — WOO_STORE_URL / WOO_CONSUMER_KEY / WOO_CONSUMER_SECRET not set");
    return;
  }

  console.log(`[WooPoller] Starting — polling every ${POLL_INTERVAL_MS / 60000} minutes`);

  // Run once immediately on startup, then every 3 minutes
  setTimeout(pollOrders, 10_000); // 10s after boot (let DB connect first)
  setInterval(pollOrders, POLL_INTERVAL_MS);
}
