CREATE TABLE `meal_log_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`mealLogId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`nameAr` varchar(255),
	`estimatedGrams` double NOT NULL DEFAULT 100,
	`portionDesc` varchar(255),
	`portionDescAr` varchar(255),
	`fdcId` int,
	`confidence` enum('high','medium','low') NOT NULL DEFAULT 'high',
	`calories` double NOT NULL DEFAULT 0,
	`protein` double NOT NULL DEFAULT 0,
	`carbs` double NOT NULL DEFAULT 0,
	`fat` double NOT NULL DEFAULT 0,
	`fiber` double NOT NULL DEFAULT 0,
	`sugar` double NOT NULL DEFAULT 0,
	`sodium` double NOT NULL DEFAULT 0,
	`per100gCalories` double NOT NULL DEFAULT 0,
	`per100gProtein` double NOT NULL DEFAULT 0,
	`per100gCarbs` double NOT NULL DEFAULT 0,
	`per100gFat` double NOT NULL DEFAULT 0,
	CONSTRAINT `meal_log_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meal_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`mealType` enum('breakfast','lunch','dinner','snack') NOT NULL,
	`loggedAt` timestamp NOT NULL DEFAULT (now()),
	`imageUrl` varchar(512),
	`notes` text,
	`insightAr` text,
	`insightEn` text,
	`totalCalories` double NOT NULL DEFAULT 0,
	`totalProtein` double NOT NULL DEFAULT 0,
	`totalCarbs` double NOT NULL DEFAULT 0,
	`totalFat` double NOT NULL DEFAULT 0,
	`totalFiber` double NOT NULL DEFAULT 0,
	`totalSugar` double NOT NULL DEFAULT 0,
	`totalSodium` double NOT NULL DEFAULT 0,
	CONSTRAINT `meal_logs_id` PRIMARY KEY(`id`)
);
